/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chathurangani.book.shop;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author Dilum
 */
public class quantitiyBox extends javax.swing.JFrame {

    /**
     * Creates new form quantitiyBox
     */
    public quantitiyBox() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("ok.png")));
        itemIs.setText(controllers.itemset[1]);
        QUANTITIY_BOX.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }
    
     public quantitiyBox(boolean returns) {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("ok.png")));
         System.out.println("hi");
        this.returns = true;
        itemIs.setText(controllers.itemset[1]);
    }
     
     boolean returns = false;
     dbConnector connect = new dbConnector();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        itemIs = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        okBtn = new javax.swing.JButton();
        QUANTITIY_BOX = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jButton5.setBackground(new java.awt.Color(0, 153, 255));
        jButton5.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("OK");

        jButton11.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        itemIs.setFont(new java.awt.Font("Arial Black", 0, 22)); // NOI18N
        itemIs.setForeground(new java.awt.Color(255, 255, 255));
        itemIs.setText("QUANTITY");

        jPanel2.setBackground(new java.awt.Color(0, 153, 0));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        okBtn.setBackground(new java.awt.Color(0, 204, 204));
        okBtn.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        okBtn.setForeground(new java.awt.Color(255, 255, 255));
        okBtn.setText("OK");
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });

        QUANTITIY_BOX.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        QUANTITIY_BOX.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                QUANTITIY_BOXKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                QUANTITIY_BOXKeyTyped(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(QUANTITIY_BOX, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(240, 240, 240)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(okBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(itemIs, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(608, 608, 608)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemIs, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(QUANTITIY_BOX)
                    .addComponent(okBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                .addGap(68, 68, 68)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 654, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void quanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quanKeyTyped

    }//GEN-LAST:event_quanKeyTyped

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
     

            try
                {
                    
                             String lenth = QUANTITIY_BOX.getText().trim();
        
                            //if quantitiy box is empty then setting value to 1
                             if(lenth.isEmpty())
                                        {
                                            MAIN_FRAME.quan = "1";
                                        }
                                    else
                                        {
                                            MAIN_FRAME.quan = lenth;
                                        }
                             recod("Entered "+lenth+" as the quantitiy of "+itemIs.getText()); 
                            QUANTITIY_BOX.setText("");
                            MAIN_FRAME.searchItemsToTable(controllers.itemset);
                            MAIN_FRAME.ContinueSearch();
                            setVisible(false);
                }
               catch(Exception e)
                {
                    //nothing
                }
              
           
    }//GEN-LAST:event_okBtnActionPerformed

    private void QUANTITIY_BOXKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QUANTITIY_BOXKeyTyped
        String lenth = QUANTITIY_BOX.getText().trim();
        char charactor = evt.getKeyChar();

        if (lenth.length() == 10) {
            evt.consume();
        }

        if ((Character.isDigit(charactor)) || (Character.isISOControl(charactor))) {
            QUANTITIY_BOX.setEditable(true);
        } else {
            evt.consume();
        }
        
        if(charactor == KeyEvent.VK_ENTER)
            {
                //for main billing panel
                if(returns == false)
                    {
                              //if quantitiy box is empty then setting value to 1
                            if(lenth.isEmpty())
                                {
                                    MAIN_FRAME.quan = "1";
                                }
                            else
                                {
                                    MAIN_FRAME.quan = lenth;
                                }
                            
                            recod("Entered "+lenth+" as the quantitiy of "+itemIs.getText()); 
                            QUANTITIY_BOX.setText("");
                            MAIN_FRAME.searchItemsToTable(controllers.itemset);
                            MAIN_FRAME.ContinueSearch();
                            
                            setVisible(false);
                    }
      
            }
    }//GEN-LAST:event_QUANTITIY_BOXKeyTyped

      void recod(String activity)
        {
            //cheking if this admin or cashier
            if(controllers.systemUser == true)
                {
                try 
                {
                    connect.recoder(activity);
                    } catch (Exception ex) {
                        Logger.getLogger(MAIN_FRAME.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
        }
    private void QUANTITIY_BOXKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QUANTITIY_BOXKeyReleased

    }//GEN-LAST:event_QUANTITIY_BOXKeyReleased

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    
 //    ALL NUMBER BUTTONS WILL CALL THIS METHOD BY CALLING THER VALUES AMOUNG THE PARAMETERS
     void returnvalue(String value)
        {
            if(returns == false)
                {
                        MAIN_FRAME.quan = value;
            
                        //calling continueSearchProcess methos in MIAN_FRAME class to continue the search process
                        MAIN_FRAME.searchItemsToTable(controllers.itemset);
                        MAIN_FRAME.ContinueSearch();
                        setVisible(false);
                }
            
        }
   

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quantitiyBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quantitiyBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quantitiyBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quantitiyBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quantitiyBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField QUANTITIY_BOX;
    private javax.swing.JLabel itemIs;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton okBtn;
    // End of variables declaration//GEN-END:variables
}
