package chathurangani.book.shop;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class returns extends javax.swing.JFrame {

    public returns() {

        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("ok.png")));
        proceed.setEnabled(false); //proceed btn
        CancelBtn.setEnabled(false);// chash price text box enabling btn
        returnAllbtn.setEnabled(false);
        cashBackBtn.setEnabled(false);
        returnBtn.setEnabled(false);
    }

    dbConnector connection = new dbConnector();

    BigDecimal totalAmount;
    BigDecimal pricePerItem;
    static BigDecimal cashPrice = new BigDecimal("0.0");
    static String quantitiy = "1";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        chekDeal = new javax.swing.JButton();
        dealIdBox = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        returnItemTable = new javax.swing.JTable();
        proceed = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        discountBox = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        totalBox = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        balanceBox = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        paymentBox = new javax.swing.JLabel();
        CancelBtn = new javax.swing.JButton();
        returnAllbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        selectedReturn = new javax.swing.JTable();
        cashBackBtn = new javax.swing.JButton();
        totalDisplay = new javax.swing.JLabel();
        returnBtn = new javax.swing.JButton();
        fullCashBack = new javax.swing.JButton();

        jLabel12.setText("Total Bill Amount");

        jLabel13.setText("Customer Name : ");

        jLabel14.setText("jLabel6");
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel15.setText("jLabel6");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Return Items");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Return Items");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 60));

        chekDeal.setText("CHECK");
        chekDeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chekDealActionPerformed(evt);
            }
        });

        dealIdBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dealIdBoxActionPerformed(evt);
            }
        });
        dealIdBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dealIdBoxKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(dealIdBox, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chekDeal, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chekDeal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dealIdBox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 490, 40));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        returnItemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Code", "Item Name", "Quantity", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        returnItemTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnItemTableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(returnItemTable);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 120, 610, 350));

        proceed.setText("PROCEED");
        proceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedActionPerformed(evt);
            }
        });
        jPanel1.add(proceed, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 480, 200, 40));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Discount Amount");

        discountBox.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        discountBox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Total Bill Amount");

        totalBox.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        totalBox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addComponent(totalBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(discountBox, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(discountBox, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(totalBox, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 190, 420, 80));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Balance");

        balanceBox.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        balanceBox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Paymentl Amount");

        paymentBox.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        paymentBox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(paymentBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(balanceBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(balanceBox, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(paymentBox, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 270, 420, 80));

        CancelBtn.setText("CANCEL");
        CancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBtnActionPerformed(evt);
            }
        });
        jPanel1.add(CancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 480, 360, 40));

        returnAllbtn.setText("RETURN ALL");
        returnAllbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnAllbtnActionPerformed(evt);
            }
        });
        jPanel1.add(returnAllbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 420, 360, 40));

        selectedReturn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SELECTED ITEMS", "Quantity", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(selectedReturn);

        jScrollPane1.setViewportView(jScrollPane2);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, 200, 350));

        cashBackBtn.setText("CASH BACK");
        cashBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashBackBtnActionPerformed(evt);
            }
        });
        jPanel1.add(cashBackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 360, 120, 40));

        totalDisplay.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        totalDisplay.setForeground(new java.awt.Color(255, 0, 0));
        totalDisplay.setText("0.0");
        jPanel1.add(totalDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 120, 380, 60));

        returnBtn.setText("RETURN");
        returnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBtnActionPerformed(evt);
            }
        });
        jPanel1.add(returnBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, 290, 40));

        fullCashBack.setText("FULL CASH BACK");
        fullCashBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullCashBackActionPerformed(evt);
            }
        });
        jPanel1.add(fullCashBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 360, 220, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void proceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedActionPerformed
        
        //updating total bill amount display label
        totalBox.setText(new BigDecimal(totalBox.getText()).subtract(new BigDecimal(totalDisplay.getText())).toString());
        
    ReturnFrame returnThis = new ReturnFrame(true);
        returnThis.setVisible(true);
        ReturnFrame.returnCash = cashPrice;
        ReturnFrame.paymentAmount.setText(totalDisplay.getText());
        dispose(); //hiding this window
        


    }//GEN-LAST:event_proceedActionPerformed

    private void chekDealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chekDealActionPerformed
        cheker(); // calling to search process
    }//GEN-LAST:event_chekDealActionPerformed

    //METHOD FOR CHEKING ENTERD BARCODE OR BILL NO FROM THE DATABASE
    void cheker() {

        String dealcode = dealIdBox.getText();
        try {

            //CLEARING TABLE 
            DefaultTableModel removedata = (DefaultTableModel) returnItemTable.getModel();
            int itemrow = returnItemTable.getRowCount();//Getting number of rows in item table to clear that all.

            while (removedata.getRowCount() > 0) {
                removedata.removeRow(0); //0 means indes of the raw [o th raw will be remove in the table]
            }

            resetData(); // restet all btn feilds
            dealDataClear(); // clear customer details

            dealIdBox.setText(dealcode); // Displaying again cleard item code in to deal chek box

            //STARTING SEARCH
            String[] name_date = connection.dealCheker(dealcode); //excpting name and datetime as a items ofa assry by calling to method in array
            totalBox.setText(name_date[2]); // setting the 1 index of returned array 'deal dqate and time' to date time name box
            discountBox.setText(name_date[3]); // setting the 2 index of returned array 'total amount of the bill' to totalamount box
            paymentBox.setText(name_date[4]);
            balanceBox.setText(name_date[5]);

            CancelBtn.setEnabled(true);
            returnAllbtn.setEnabled(true);
            cashBackBtn.setEnabled(true);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Something went wrong !");
        }

    }
    private void dealIdBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dealIdBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dealIdBoxActionPerformed

    private void returnItemTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnItemTableMouseClicked
        returnBtn.setEnabled(true);
    }//GEN-LAST:event_returnItemTableMouseClicked

    private void CancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBtnActionPerformed

        resetData(); // reset the interface
        dealDataClear(); // celar deal data (customer name , phone number , total bill amount etc..)

    }//GEN-LAST:event_CancelBtnActionPerformed

    private void returnAllbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnAllbtnActionPerformed
        // discount will be cancledd when item returning

        BigDecimal amount = new BigDecimal(paymentBox.getText()); // getting total amount

        ReturnFrame returnThis = new ReturnFrame(true);
        returnThis.setVisible(true);
        returnThis.paymentAmount.setText(amount.toString());
        resetData();
        dealDataClear();
        dispose(); //hiding this window
        
        
    }//GEN-LAST:event_returnAllbtnActionPerformed

    private void returnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBtnActionPerformed

        DefaultTableModel itemdata = (DefaultTableModel) returnItemTable.getModel(); //table model of main retrun item displaying table
        int row = returnItemTable.getSelectedRow();

        DefaultTableModel selectData = (DefaultTableModel) selectedReturn.getModel(); //table model of selected return item table model
        String[] put_item_to_return = {(String) returnItemTable.getValueAt(row, 0)};
        selectData.addRow(put_item_to_return);

        BigDecimal totalamount = new BigDecimal((String) returnItemTable.getValueAt(row, 3));
        BigDecimal price_per_item_is = totalamount.divide(new BigDecimal((String) returnItemTable.getValueAt(row, 2)));

        String input = "";

        returnQuan getQuan = new returnQuan(price_per_item_is);
        getQuan.setVisible(true);

    }//GEN-LAST:event_returnBtnActionPerformed

    private void cashBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashBackBtnActionPerformed

        BigDecimal totalpriceAmount = new BigDecimal(totalDisplay.getText().trim());
        
        //updating total bill amount display label
        totalBox.setText(new BigDecimal(totalBox.getText()).subtract(new BigDecimal(totalDisplay.getText())).toString());
        try {
            //cheking is date avaible()

            boolean dateAvailability = connection.passdate(String.valueOf(java.time.LocalDate.now()));

            //if date is not exsit in database then create new row for the date either update exsising dat row
            if (dateAvailability == true) {
                // adding new cashprice amount and sellprice amount to prevois cashprice and sell price amount
                //new cash price and sell price amounts are holded in controller class cashPrice and sellPrice variables
                BigDecimal updated_outPrice = cashPrice.add(controllers.out);
                BigDecimal updated_outsell = new BigDecimal(totalDisplay.getText().trim()).add(controllers.sell);
                connection.incomedata_outUpdater(String.valueOf(updated_outPrice), String.valueOf(updated_outsell), String.valueOf(java.time.LocalDate.now()));
                JOptionPane.showMessageDialog(null, "CASH BACK AMOUNT IS \n Rs . " + totalDisplay.getText()); // setting non discounted value to total display box
                cashPrice = new BigDecimal("0.0");
                totalDisplay.setText("0.0");

            } else {
                String ouprice_is = String.valueOf(cashPrice);
                connection.Strore_incomedata("0.0", "0.0", ouprice_is, totalDisplay.getText().trim(), String.valueOf(java.time.LocalDate.now()));
                JOptionPane.showMessageDialog(null, "CASH BACK AMOUNT IS \n Rs . " + totalDisplay.getText()); // setting non discounted value to total display box
                cashPrice = new BigDecimal("0.0");
                totalDisplay.setText("0.0");
            }
        } catch (Exception ex) {
            Logger.getLogger(MAIN_FRAME.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_cashBackBtnActionPerformed

    private void dealIdBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dealIdBoxKeyTyped
        char charactor = evt.getKeyChar();

        if (charactor == KeyEvent.VK_ENTER) {
            cheker();
        }
    }//GEN-LAST:event_dealIdBoxKeyTyped

    private void fullCashBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullCashBackActionPerformed
        try {
            DefaultTableModel fullcash = (DefaultTableModel) returnItemTable.getModel();
            int rowcount = fullcash.getRowCount();
            for (int i = 0; i < rowcount; i++) {
                
                //generating total cash price of items
                BigDecimal item_Cprice = new BigDecimal(connection.searchItemPrice(returnItemTable.getValueAt(i, 0).toString())).multiply(new BigDecimal(returnItemTable.getValueAt(i, 2).toString()));
                cashPrice = cashPrice.add(item_Cprice);

                //updating stock items
                int stock = connection.searchItemStock(returnItemTable.getValueAt(i, 0).toString()); //cheking for current stock
                stock = stock + Integer.parseInt(returnItemTable.getValueAt(i, 2).toString()); //updatin stock
                connection.updateStockitems("stock", String.valueOf(stock), returnItemTable.getValueAt(i, 0).toString());
                
                
                resetData();
                dealDataClear();
            }

            boolean dateAvailability = connection.passdate(String.valueOf(java.time.LocalDate.now()));

            //if date is not exsit in database then create new row for the date either update exsising dat row
            if (dateAvailability == true) {
                // adding new cashprice amount and sellprice amount to prevois cashprice and sell price amount
                //new cash price and sell price amounts are holded in controller class cashPrice and sellPrice variables
                BigDecimal updated_outPrice = new BigDecimal("0.0");
                BigDecimal updated_outsell = new BigDecimal("0.0");
                try 
                    {
                        updated_outPrice = cashPrice.add(controllers.out);
                    }
                catch(Exception e)
                    {
                        updated_outPrice = new BigDecimal("0.0");
                    }
                 try 
                    {
                        updated_outsell = new BigDecimal(totalBox.getText().trim()).add(controllers.sell);
                    }
                catch(Exception e)
                    {
                        updated_outsell = new BigDecimal("0.0");
                    }
                
                
                connection.incomedata_outUpdater(String.valueOf(updated_outPrice), String.valueOf(updated_outsell), String.valueOf(java.time.LocalDate.now()));
                JOptionPane.showMessageDialog(null, "CASH BACK AMOUNT IS \n Rs . " + totalBox.getText()); // setting non discounted value to total display box
                cashPrice = new BigDecimal("0.0");
                totalDisplay.setText("0.0");
            } else {
                connection.Strore_incomedata("0.0", "0.0", cashPrice.toString(), totalBox.getText().trim(), String.valueOf(java.time.LocalDate.now()));
                JOptionPane.showMessageDialog(null, "CASH BACK AMOUNT IS \n Rs . " + totalBox.getText()); // setting non discounted value to total display box
                cashPrice = new BigDecimal("0.0");
                totalDisplay.setText("0.0");
            }
        } catch (Exception ex) {
            Logger.getLogger(MAIN_FRAME.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_fullCashBackActionPerformed

    static BigDecimal returnCount(BigDecimal priceItem, int quan) {
        BigDecimal updatePrice = priceItem.multiply(new BigDecimal(quan));
        BigDecimal currentTotal = new BigDecimal(totalDisplay.getText().toString());
        totalDisplay.setText(String.valueOf(updatePrice.add(currentTotal)));
        
         return new BigDecimal("0.0");
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(returns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(returns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(returns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(returns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new returns().setVisible(true);
            }
        });
    }

    public static void dealItemsToTable(String icode, String iname, String quantity, String price) {
        String[] itemdata = {icode, iname, quantity, price};
        DefaultTableModel setData = (DefaultTableModel) returnItemTable.getModel();
        setData.addRow(itemdata);
    }

    static void resetData() // this fumction will reset all text feilds and reset all btns
    {
         //CLEARING TABLE
        DefaultTableModel itemdata = (DefaultTableModel) returnItemTable.getModel(); //table model of main retrun item displaying table
        DefaultTableModel selectData = (DefaultTableModel) selectedReturn.getModel(); //table model of selected return item table model

        while (itemdata.getRowCount() > 0) {
            itemdata.removeRow(0);
        }

        while (selectData.getRowCount() > 0) {
            selectData.removeRow(0);
        }
        
        
        dealIdBox.setText(""); // clear search bar
        proceed.setEnabled(false); //disabaling proceed btn
        returnBtn.setEnabled(false); //disabling return btn
    }

    //Clear all customer details
    static void dealDataClear() {
        totalBox.setText("");
        discountBox.setText("");
        paymentBox.setText("");
        balanceBox.setText("");
        totalDisplay.setText("0.0");
        cashPrice = new BigDecimal("0.0");

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelBtn;
    public static javax.swing.JLabel balanceBox;
    private javax.swing.JButton cashBackBtn;
    public static javax.swing.JButton chekDeal;
    public static javax.swing.JTextField dealIdBox;
    public static javax.swing.JLabel discountBox;
    private javax.swing.JButton fullCashBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    public static javax.swing.JLabel paymentBox;
    public static javax.swing.JButton proceed;
    private javax.swing.JButton returnAllbtn;
    public static javax.swing.JButton returnBtn;
    public static javax.swing.JTable returnItemTable;
    public static javax.swing.JTable selectedReturn;
    public static javax.swing.JLabel totalBox;
    public static javax.swing.JLabel totalDisplay;
    // End of variables declaration//GEN-END:variables
}
