package chathurangani.book.shop;


import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dilum
 */
public class stock_item_display extends javax.swing.JFrame {

    /**
     * Creates new form stock_item_display
     */
    public stock_item_display(String code , String name , String sprice , String stocksize , String table) {
        
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("ok.png")));
         this.itemData[0]=code;
         this.itemData[1]=name;
         this.itemData[3]=sprice;
         this.itemData[4]=stocksize;
  
        
        itemCodeBox.setText(code);
        itemNameBox.setText(name);
        sellingPriceBox.setText(sprice);
        stockBox.setText(stocksize);
       
        
        itemCodeBox.setEditable(false);
        itemNameBox.setEditable(false);
        sellingPriceBox.setEditable(false);
        stockBox.setEditable(false);
        
        codeupdate.setEnabled(false);
        nameupdate.setEnabled(false);
        spriceupdate.setEnabled(false);
        stockupdate.setEnabled(false);
        
        ok1.setVisible(false);
        ok2.setVisible(false);
        ok4.setVisible(false);
        ok5.setVisible(false);
        
        this.primarykeyofdata=code;
        
        this.table = table;
 
    }
    
        public stock_item_display(String code , String name , String stocksize , String table) {
        
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("ok.png")));
         this.itemData[0]=code;
         this.itemData[1]=name;
         this.itemData[4]=stocksize;
  
        
        itemCodeBox.setText(code);
        itemNameBox.setText(name);
        stockBox.setText(stocksize);
       
        lbl_sprice.setVisible(false);
        itemCodeBox.setEditable(false);
        itemNameBox.setEditable(false);
        sellingPriceBox.setVisible(false);
        stockBox.setEditable(false);
        
        codeupdate.setEnabled(false);
        nameupdate.setEnabled(false);
        spriceupdate.setVisible(false);
        stockupdate.setEnabled(false);
        spriceedit.setVisible(false);
        
        ok1.setVisible(false);
        ok2.setVisible(false);
        ok4.setVisible(false);
        ok5.setVisible(false);
        
        this.primarykeyofdata=code;
        
        this.table = table;
 
    }
    
    dbConnector connect = new dbConnector();

    String primarykeyofdata ;
    String WhatIsCondition;
    
     // thisarraycontain default values of the item for later use
    String [] itemData = new String[5];
    boolean dot;
    static String table; //tab index;
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        itemCodeBox = new javax.swing.JTextField();
        itemNameBox = new javax.swing.JTextField();
        stockAdder = new javax.swing.JTextField();
        stockBox = new javax.swing.JTextField();
        CloseUpdatePannel = new javax.swing.JButton();
        codeedit = new javax.swing.JButton();
        codeupdate = new javax.swing.JButton();
        nameedit = new javax.swing.JButton();
        nameupdate = new javax.swing.JButton();
        stockAddBtn = new javax.swing.JButton();
        spriceedit = new javax.swing.JButton();
        stockupdate = new javax.swing.JButton();
        lbl_sprice = new javax.swing.JLabel();
        sellingPriceBox = new javax.swing.JTextField();
        stocksedit = new javax.swing.JButton();
        spriceupdate = new javax.swing.JButton();
        ok2 = new javax.swing.JLabel();
        ok4 = new javax.swing.JLabel();
        ok1 = new javax.swing.JLabel();
        ok5 = new javax.swing.JLabel();
        stockAddBtn1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jTextField9.setText("jTextField1");

        jTextField10.setText("jTextField1");

        jButton6.setText("jButton2");

        jButton8.setText("jButton2");

        jButton19.setText("jButton19");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Item Viewer");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("ITEM CODE ");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("ITEM NAME");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Add Stock");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Add more stocks ");

        itemCodeBox.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        itemCodeBox.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        itemCodeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCodeBoxActionPerformed(evt);
            }
        });
        itemCodeBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                itemCodeBoxKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                itemCodeBoxKeyTyped(evt);
            }
        });

        itemNameBox.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        itemNameBox.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        itemNameBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                itemNameBoxKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                itemNameBoxKeyTyped(evt);
            }
        });

        stockAdder.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        stockAdder.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        stockAdder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockAdderActionPerformed(evt);
            }
        });
        stockAdder.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                stockAdderKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                stockAdderKeyTyped(evt);
            }
        });

        stockBox.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        stockBox.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        stockBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                stockBoxKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                stockBoxKeyTyped(evt);
            }
        });

        CloseUpdatePannel.setBackground(new java.awt.Color(51, 51, 51));
        CloseUpdatePannel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        CloseUpdatePannel.setForeground(new java.awt.Color(255, 255, 255));
        CloseUpdatePannel.setText("CLOSE  PANEL");
        CloseUpdatePannel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CloseUpdatePannel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseUpdatePannelActionPerformed(evt);
            }
        });

        codeedit.setBackground(new java.awt.Color(255, 0, 0));
        codeedit.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        codeedit.setForeground(new java.awt.Color(255, 255, 255));
        codeedit.setText("Edit");
        codeedit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        codeedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeeditActionPerformed(evt);
            }
        });

        codeupdate.setBackground(new java.awt.Color(0, 204, 204));
        codeupdate.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        codeupdate.setForeground(new java.awt.Color(255, 255, 255));
        codeupdate.setText("UPDATE");
        codeupdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        codeupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeupdateActionPerformed(evt);
            }
        });

        nameedit.setBackground(new java.awt.Color(255, 0, 0));
        nameedit.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        nameedit.setForeground(new java.awt.Color(255, 255, 255));
        nameedit.setText("Edit");
        nameedit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nameedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameeditActionPerformed(evt);
            }
        });

        nameupdate.setBackground(new java.awt.Color(0, 204, 204));
        nameupdate.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        nameupdate.setForeground(new java.awt.Color(255, 255, 255));
        nameupdate.setText("UPDATE");
        nameupdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nameupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameupdateActionPerformed(evt);
            }
        });

        stockAddBtn.setBackground(new java.awt.Color(255, 0, 0));
        stockAddBtn.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        stockAddBtn.setForeground(new java.awt.Color(255, 255, 255));
        stockAddBtn.setText("+");
        stockAddBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        stockAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockAddBtnActionPerformed(evt);
            }
        });
        stockAddBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                stockAddBtnKeyPressed(evt);
            }
        });

        spriceedit.setBackground(new java.awt.Color(255, 0, 0));
        spriceedit.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        spriceedit.setForeground(new java.awt.Color(255, 255, 255));
        spriceedit.setText("Edit");
        spriceedit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        spriceedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spriceeditActionPerformed(evt);
            }
        });

        stockupdate.setBackground(new java.awt.Color(0, 204, 204));
        stockupdate.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        stockupdate.setForeground(new java.awt.Color(255, 255, 255));
        stockupdate.setText("UPDATE");
        stockupdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        stockupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockupdateActionPerformed(evt);
            }
        });

        lbl_sprice.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_sprice.setForeground(new java.awt.Color(102, 102, 102));
        lbl_sprice.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_sprice.setText("SELL PRICE ");

        sellingPriceBox.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        sellingPriceBox.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        sellingPriceBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sellingPriceBoxKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sellingPriceBoxKeyTyped(evt);
            }
        });

        stocksedit.setBackground(new java.awt.Color(255, 0, 0));
        stocksedit.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        stocksedit.setForeground(new java.awt.Color(255, 255, 255));
        stocksedit.setText("Edit");
        stocksedit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        stocksedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockseditActionPerformed(evt);
            }
        });

        spriceupdate.setBackground(new java.awt.Color(0, 204, 204));
        spriceupdate.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        spriceupdate.setForeground(new java.awt.Color(255, 255, 255));
        spriceupdate.setText("UPDATE");
        spriceupdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        spriceupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spriceupdateActionPerformed(evt);
            }
        });

        ok2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_package/images/tick.png"))); // NOI18N

        ok4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_package/images/tick.png"))); // NOI18N

        ok1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_package/images/tick.png"))); // NOI18N

        ok5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_package/images/tick.png"))); // NOI18N

        stockAddBtn1.setBackground(new java.awt.Color(255, 0, 0));
        stockAddBtn1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        stockAddBtn1.setForeground(new java.awt.Color(255, 255, 255));
        stockAddBtn1.setText("-");
        stockAddBtn1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        stockAddBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockAddBtn1ActionPerformed(evt);
            }
        });
        stockAddBtn1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                stockAddBtn1KeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("STOCKS    ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(itemCodeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(codeedit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(codeupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ok1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(itemNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(nameedit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(nameupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ok2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(lbl_sprice)
                                        .addGap(35, 35, 35)
                                        .addComponent(sellingPriceBox, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(spriceedit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(spriceupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ok4))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(120, 120, 120)
                                        .addComponent(stockBox, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(stocksedit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(stockupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ok5))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(stockAdder, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(stockAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(stockAddBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(CloseUpdatePannel, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemCodeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codeedit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codeupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ok1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameedit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ok2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_sprice, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sellingPriceBox, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spriceedit, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(spriceupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ok4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(stockBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(stocksedit, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(stockupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(ok5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(stockAdder, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(stockAddBtn1)
                        .addComponent(stockAddBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(CloseUpdatePannel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 610, 420));

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("View Items & Update");

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_package/images/unnamed.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 678, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1124, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void stockupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockupdateActionPerformed
        try {
            connect.updateStockitems(table,"stock",stockBox.getText().trim(),primarykeyofdata);
            this.itemData[4] = stockBox.getText().trim();
            ok5.setVisible(true);
            connect.stockItemsShowAll(); 
            recod("Updated Item stock by -"+stockBox.getText().trim());
 
             boolean out = connect.stockout();

                if(out == true)
                       {   
                             MAIN_FRAME.bell.setVisible(true);
                       }
                else
                      {
                             MAIN_FRAME.bell.setVisible(false);
                      }
        } catch (Exception ex) {
           JOptionPane.showMessageDialog(null, " Something went wrong - StockUpdate#622! ");
           connect.recod_error(ex.toString()+"- stockItemUpdate 622 ");
        }

        stockupdate.setEnabled(false);
        stockBox.setEditable(false);

    }//GEN-LAST:event_stockupdateActionPerformed

    private void spriceeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spriceeditActionPerformed
        sellingPriceBox.setEditable(true);

        itemCodeBox.setEditable(false);
        itemNameBox.setEditable(false);
        stockBox.setEditable(false);

        codeupdate.setEnabled(false);
        nameupdate.setEnabled(false);
        spriceupdate.setEnabled(false);
        stockupdate.setEnabled(false);
    }//GEN-LAST:event_spriceeditActionPerformed

    private void stockAddBtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stockAddBtnKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockAddBtnKeyPressed

    private void stockAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockAddBtnActionPerformed

        if(stockAdder.getText().length() > 0 || stockAdder.getText().length() > 0)
            {
            
                       try {
                           
                           //geting values from new upted box and current stock box and setting agin to current stock box and sending to databse
                            stockBox.setText(String.valueOf(Integer.parseInt(stockAdder.getText()) + Integer.parseInt(stockBox.getText())));
                            connect.updateStockitems(table,"stock",stockBox.getText().trim(),primarykeyofdata);
                            recod("Increased stock by - "+stockAdder);
                            boolean out = connect.stockout();

                            if(out == true)
                                   {   
                                         MAIN_FRAME.bell.setVisible(true);
                                   }
                            else
                                  {
                                         MAIN_FRAME.bell.setVisible(false);
                                  }
                            
                        } catch (Exception ex) {
                           JOptionPane.showMessageDialog(null, " Something went wrong - StockUpdate#671! ");
                           connect.recod_error(ex.toString()+"- stockItemUpdate 671 ");
                        }
                
            }
    
        stockAdder.setText("");

    }//GEN-LAST:event_stockAddBtnActionPerformed

    private void nameupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameupdateActionPerformed
         try {
            connect.updateStockitems(table,"name",itemNameBox.getText().trim(),primarykeyofdata);
            this.itemData[1]=itemNameBox.getText().trim();
            ok2.setVisible(true);
            connect.stockItemsShowAll(); 
            recod("Updated Item name by -"+itemNameBox.getText().trim());
        }
        catch (Exception ex) {
           JOptionPane.showMessageDialog(null, " Something went wrong - StockUpdate#690! ");
           connect.recod_error(ex.toString()+"- stockItemUpdate 622 ");
        }

        nameupdate.setEnabled(false);
        itemNameBox.setEditable(false);
    }//GEN-LAST:event_nameupdateActionPerformed

    private void nameeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameeditActionPerformed
        itemNameBox.setEditable(true);
        
        itemCodeBox.setEditable(false);
        sellingPriceBox.setEditable(false);
        stockBox.setEditable(false);

        codeupdate.setEnabled(false);
        spriceupdate.setEnabled(false);
        stockupdate.setEnabled(false);
    }//GEN-LAST:event_nameeditActionPerformed

    private void codeupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeupdateActionPerformed

        try {
 
            connect.updateStockitems(table,"itemcode",itemCodeBox.getText().trim(),primarykeyofdata);
            this.itemData[0]=itemCodeBox.getText().trim();
            primarykeyofdata = itemCodeBox.getText().trim(); // setting new primary key
            ok1.setVisible(true);
            connect.stockItemsShowAll(); 
            recod("Updated Item code by -"+itemCodeBox.getText().trim());
        }

             catch (SQLException ex) {
                 JOptionPane.showMessageDialog(null, "Please select another ITEM CODE , This Item Code is already in your stocks !", "Same Item Code Found ",JOptionPane.WARNING_MESSAGE);
                 itemCodeBox.setText(" ");
                 connect.recod_error(ex.toString()+" this is not a error ,  stockItemUpdate 725 ");
        }
        
        catch(Exception e)
        {
                JOptionPane.showMessageDialog(null , "Enter valid data !");
                connect.recod_error(e.toString()+" this is not a error , stockItemUpdate 622 ");
        }        
        
        

        codeupdate.setEnabled(false);
        itemCodeBox.setEditable(false);
    }//GEN-LAST:event_codeupdateActionPerformed

    private void codeeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeeditActionPerformed
        itemCodeBox.setEditable(true);

        itemNameBox.setEditable(false);
        stockBox.setEditable(false);
        stockBox.setEditable(false);
        sellingPriceBox.setEditable(false);
        
        nameupdate.setEnabled(false);
        spriceupdate.setEnabled(false);
        stockupdate.setEnabled(false);
        
        if(itemNameBox.getText().trim().equals(""))
            {
                itemNameBox.setText(itemData[1]);
            }
        if(stockAdder.getText().trim().isEmpty())
            {
                stockAdder.setText(itemData[2]);
            }
        if(sellingPriceBox.getText().trim().isEmpty())
            {
                sellingPriceBox.setText(itemData[3]);
            }
        if(stockBox.getText().trim().isEmpty())
            {
                stockBox.setText(itemData[4]);
            }
        
    }//GEN-LAST:event_codeeditActionPerformed

    private void CloseUpdatePannelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseUpdatePannelActionPerformed
   
        try {
            //DISPLAYING UPDATE TABLE TO THE USER
            stocks.clearTable();
            connect.stockItemsShowAll();
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, " Something went wrong - StockUpdate#779! ");
            connect.recod_error(e.toString()+"- stockItemUpdate 779 ");
        }
        
         setVisible(false);

    }//GEN-LAST:event_CloseUpdatePannelActionPerformed

    private void stockBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stockBoxKeyTyped
        char character = evt.getKeyChar();
        String lenth = stockBox.getText();

        if(lenth.length()==10)
        {
            evt.consume();
        }

        if((Character.isDigit(character)) || Character.isISOControl(character) && lenth.length()>1)
        {
            stockBox.setEnabled(true);
            stockupdate.setEnabled(true);
        }
        else
        {
            evt.consume();
            stockupdate.setEnabled(false);
        }
    }//GEN-LAST:event_stockBoxKeyTyped

    private void stockBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stockBoxKeyReleased
        String lenth=stockBox.getText();
        if(lenth.length()>0)
        {
            stockupdate.setEnabled(true);
        }
        else
        {
            stockupdate.setEnabled(false);
        }
    }//GEN-LAST:event_stockBoxKeyReleased

    private void stockAdderKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stockAdderKeyTyped
        char charactor = evt.getKeyChar();
        String lenth = stockAdder.getText();

        if(lenth.length()==16)
        {
            evt.consume();
        }
        
          
    //CHAKING IF ALREADY " . " IN TEXT BOX
        if(!lenth.contains("."))
            {
                dot=false;
                
            }

         // IF DOT HAS TYPED THIS PART WILL BW RUN
        if(dot == false)
            {
                            if ((Character.isDigit(charactor)) || (Character.isISOControl(charactor)) || charactor == KeyEvent.VK_PERIOD)
                            {
                               stockAdder.setEditable(true);
                                
                            } else {
                                
                               evt.consume();
                            }
                             
            }
        
        else
            {
   // IF DOT DOES NOT HAS TYPED THIS PART WILL RUN
                            if ((Character.isDigit(charactor)) || (Character.isISOControl(charactor)) )
                                {
                                    if(lenth.length() == lenth.indexOf(".")+3)
                                        {
                                         evt.consume();
                                        }
                                }
                            else
                                {
                                       evt.consume();
                                }
            }
   

    //MAKE dot VARIABLE TRUE IF USER PRESSED " . "
        if(charactor == KeyEvent.VK_PERIOD)
            {
                dot = true;
           }

    
    
    }//GEN-LAST:event_stockAdderKeyTyped

    private void stockAdderKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stockAdderKeyReleased
        String lenth = stockAdder.getText();

        if(lenth.length()>0)
        {
            stockAddBtn.setEnabled(true);
        }
        else
        {
            stockAddBtn.setEnabled(false);
        }
    }//GEN-LAST:event_stockAdderKeyReleased

    private void stockAdderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockAdderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockAdderActionPerformed

    private void itemNameBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemNameBoxKeyTyped

        String lenth = itemNameBox.getText();

        if(lenth.length()==100)
        {
            evt.consume();
        }

    }//GEN-LAST:event_itemNameBoxKeyTyped

    private void itemNameBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemNameBoxKeyReleased
        String lenth = itemNameBox.getText();

        if(lenth.length()>0)
        {
            nameupdate.setEnabled(true);
        }
        else
        {
            nameupdate.setEnabled(false);
        }
    }//GEN-LAST:event_itemNameBoxKeyReleased

    private void itemCodeBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemCodeBoxKeyTyped
        String lenth = itemCodeBox.getText();

        if(lenth.length()==30)
        {
            evt.consume();
        }

    }//GEN-LAST:event_itemCodeBoxKeyTyped

    private void itemCodeBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemCodeBoxKeyReleased
        String lenth = itemCodeBox.getText();

        if(lenth.length()>0)
        {
            codeupdate.setEnabled(true);
        }
        else
        {
            codeupdate.setEnabled(false);
        }
    }//GEN-LAST:event_itemCodeBoxKeyReleased

    private void itemCodeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCodeBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemCodeBoxActionPerformed

    private void sellingPriceBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sellingPriceBoxKeyReleased
        String lenth = sellingPriceBox.getText();

        if(lenth.length()>0)
        {
            spriceupdate.setEnabled(true);
        }
        else
        {
            spriceupdate.setEnabled(false);
        }
    }//GEN-LAST:event_sellingPriceBoxKeyReleased

    private void sellingPriceBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sellingPriceBoxKeyTyped
         char character = evt.getKeyChar();
        String lenth = sellingPriceBox.getText();

        if(lenth.length()==10)
        {
            evt.consume();
        }

        if((Character.isDigit(character)) || Character.isISOControl(character) && lenth.length()>1 || character==KeyEvent.VK_PERIOD)
        {
            sellingPriceBox.setEnabled(true);
            spriceupdate.setEnabled(true);
        }
        else
        {
            evt.consume();
            spriceupdate.setEnabled(false);
        }
    }//GEN-LAST:event_sellingPriceBoxKeyTyped

    private void stockseditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockseditActionPerformed
        stockBox.setEditable(true);
        
        itemCodeBox.setEditable(false);
        itemNameBox.setEditable(false);
        sellingPriceBox.setEditable(false);
        
        codeupdate.setEnabled(false);
        nameupdate.setEnabled(false);
        spriceupdate.setEnabled(false);
        stockupdate.setEnabled(false);
        
        
    }//GEN-LAST:event_stockseditActionPerformed

    private void spriceupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spriceupdateActionPerformed
          try {
              
            BigDecimal selprice = new BigDecimal(sellingPriceBox.getText().trim());
            connect.updateStockitems(table,"sellprice",selprice.toString(),primarykeyofdata);
            this.itemData[3]=sellingPriceBox.getText().trim();
            ok4.setVisible(true);
            connect.stockItemsShowAll(); 
            recod("Updated Item price by -"+sellingPriceBox.getText().trim());
            
        } catch (Exception ex) {
          JOptionPane.showMessageDialog(null, " Something went wrong - StockUpdate#1006! ");
          connect.recod_error(ex.toString()+"- stockItemUpdate 1006 ");
        }

        spriceupdate.setEnabled(false);
        sellingPriceBox.setEditable(false);
    }//GEN-LAST:event_spriceupdateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         //seting all fields to default values
        itemCodeBox.setText(itemData[0]);
        itemNameBox.setText(itemData[1]);
        stockAdder.setText(itemData[2]);
        sellingPriceBox.setText(itemData[3]);
        stockBox.setText(itemData[4]);
        recod("Refreshed stock item updator window");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void stockAddBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockAddBtn1ActionPerformed
        if(stockAdder.getText().length() > 0 || stockAdder.getText().length() > 0)
            {
            
                       try {
                           
                           //geting values from new upted box and current stock box and setting agin to current stock box and sending to databse
                            stockBox.setText(String.valueOf( Integer.parseInt(stockBox.getText()) - Integer.parseInt(stockAdder.getText())));
                            connect.updateStockitems(table,"stock",stockBox.getText().trim(),primarykeyofdata);
                            recod("Decreased stock by - "+stockAdder);
                            boolean out = connect.stockout();

                            if(out == true)
                                   {   
                                         MAIN_FRAME.bell.setVisible(true);
                                   }
                            else
                                  {
                                         MAIN_FRAME.bell.setVisible(false);
                                  }
                            
                        } catch (Exception ex) {
                           JOptionPane.showMessageDialog(null, " Something went wrong - StockUpdate#1046! ");
                           connect.recod_error(ex.toString()+"- stockItemUpdate 1046 ");
                        }
                
            }
    
        stockAdder.setText("");
    }//GEN-LAST:event_stockAddBtn1ActionPerformed

    private void stockAddBtn1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stockAddBtn1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockAddBtn1KeyPressed

      void recod(String activity)
        {
            //cheking if this admin or cashier
            if(controllers.systemUser == true)
                {
                try 
                {
                    connect.recoder(activity);
                    } catch (Exception ex) {
                         JOptionPane.showMessageDialog(null, " Your storage may be running out - StockUpdate#1068! ");
                         connect.recod_error(ex.toString()+"- stockItemUpdate 1069 ");
                        //Logger.getLogger(MAIN_FRAME.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
        }
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        dbConnector connect = new dbConnector();
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            
            JOptionPane.showMessageDialog(null, " Something went wrong - StockUpdate#1095! ");
            connect.recod_error(ex.toString()+"- stockItemUpdate 1095 ");
            //java.util.logging.Logger.getLogger(stock_item_display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try
                   {
                       new stock_item_display("","","","","").setVisible(true);
                   }
                catch(Exception e)
                    {
                        JOptionPane.showMessageDialog(null, " Something went wrong - StockUpdate#1111! ");
                        connect.recod_error(e.toString()+"- stockItemUpdate 1111 ");
                    }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseUpdatePannel;
    private javax.swing.JButton codeedit;
    private javax.swing.JButton codeupdate;
    public static javax.swing.JTextField itemCodeBox;
    private javax.swing.JTextField itemNameBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel lbl_sprice;
    private javax.swing.JButton nameedit;
    private javax.swing.JButton nameupdate;
    private javax.swing.JLabel ok1;
    private javax.swing.JLabel ok2;
    private javax.swing.JLabel ok4;
    private javax.swing.JLabel ok5;
    private javax.swing.JTextField sellingPriceBox;
    private javax.swing.JButton spriceedit;
    private javax.swing.JButton spriceupdate;
    private javax.swing.JButton stockAddBtn;
    private javax.swing.JButton stockAddBtn1;
    private javax.swing.JTextField stockAdder;
    private javax.swing.JTextField stockBox;
    private javax.swing.JButton stocksedit;
    private javax.swing.JButton stockupdate;
    // End of variables declaration//GEN-END:variables
}
