package chathurangani.book.shop;


import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dilum
 */
public class stock_item_display extends javax.swing.JFrame {

    /**
     * Creates new form stock_item_display
     */
    public stock_item_display(String code , String name , String cprice , String sprice , String stocksize) {
        
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("ok.png")));
         this.itemData[0]=code;
         this.itemData[1]=name;
         this.itemData[2]=cprice;
         this.itemData[3]=sprice;
         this.itemData[4]=stocksize;
  
        
        itemCodeBox.setText(code);
        itemNameBox.setText(name);
        cashPriceBox.setText(cprice);
        sellingPriceBox.setText(sprice);
        stockBox.setText(stocksize);
       
        
        itemCodeBox.setEditable(false);
        itemNameBox.setEditable(false);
        cashPriceBox.setEditable(false);
        sellingPriceBox.setEditable(false);
        stockBox.setEditable(false);
        
        codeupdate.setEnabled(false);
        nameupdate.setEnabled(false);
        cpriceupdate.setEnabled(false);
        spriceupdate.setEnabled(false);
        stockupdate.setEnabled(false);
        
        ok1.setVisible(false);
        ok2.setVisible(false);
        ok3.setVisible(false);
        ok4.setVisible(false);
        ok5.setVisible(false);
        
        this.primarykeyofdata=code;
    }
    
    dbConnector connect = new dbConnector();

    String primarykeyofdata ;
    String WhatIsCondition;
    
     // thisarraycontain default values of the item for later use
    String [] itemData = new String[5];
    boolean dot;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        itemCodeBox = new javax.swing.JTextField();
        itemNameBox = new javax.swing.JTextField();
        cashPriceBox = new javax.swing.JTextField();
        stockBox = new javax.swing.JTextField();
        CloseUpdatePannel = new javax.swing.JButton();
        codeedit = new javax.swing.JButton();
        codeupdate = new javax.swing.JButton();
        nameedit = new javax.swing.JButton();
        nameupdate = new javax.swing.JButton();
        cpriceedit = new javax.swing.JButton();
        cpriceupdate = new javax.swing.JButton();
        spriceedit = new javax.swing.JButton();
        stockupdate = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        sellingPriceBox = new javax.swing.JTextField();
        stocksedit = new javax.swing.JButton();
        spriceupdate = new javax.swing.JButton();
        ok2 = new javax.swing.JLabel();
        ok3 = new javax.swing.JLabel();
        ok4 = new javax.swing.JLabel();
        ok1 = new javax.swing.JLabel();
        ok5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jTextField9.setText("jTextField1");

        jTextField10.setText("jTextField1");

        jButton6.setText("jButton2");

        jButton8.setText("jButton2");

        jButton19.setText("jButton19");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Item Viewer");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("ITEM CODE ");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("ITEM NAME");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("CASH PRICE   ");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("STOCKS    ");

        itemCodeBox.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        itemCodeBox.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        itemCodeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCodeBoxActionPerformed(evt);
            }
        });
        itemCodeBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                itemCodeBoxKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                itemCodeBoxKeyTyped(evt);
            }
        });

        itemNameBox.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        itemNameBox.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        itemNameBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                itemNameBoxKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                itemNameBoxKeyTyped(evt);
            }
        });

        cashPriceBox.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cashPriceBox.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        cashPriceBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashPriceBoxActionPerformed(evt);
            }
        });
        cashPriceBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cashPriceBoxKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cashPriceBoxKeyTyped(evt);
            }
        });

        stockBox.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        stockBox.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        stockBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                stockBoxKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                stockBoxKeyTyped(evt);
            }
        });

        CloseUpdatePannel.setBackground(new java.awt.Color(51, 51, 51));
        CloseUpdatePannel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        CloseUpdatePannel.setForeground(new java.awt.Color(255, 255, 255));
        CloseUpdatePannel.setText("CLOSE  PANNEL");
        CloseUpdatePannel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CloseUpdatePannel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseUpdatePannelActionPerformed(evt);
            }
        });

        codeedit.setBackground(new java.awt.Color(255, 0, 0));
        codeedit.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        codeedit.setForeground(new java.awt.Color(255, 255, 255));
        codeedit.setText("Edit");
        codeedit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        codeedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeeditActionPerformed(evt);
            }
        });

        codeupdate.setBackground(new java.awt.Color(0, 204, 204));
        codeupdate.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        codeupdate.setForeground(new java.awt.Color(255, 255, 255));
        codeupdate.setText("UPDATE");
        codeupdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        codeupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeupdateActionPerformed(evt);
            }
        });

        nameedit.setBackground(new java.awt.Color(255, 0, 0));
        nameedit.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        nameedit.setForeground(new java.awt.Color(255, 255, 255));
        nameedit.setText("Edit");
        nameedit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nameedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameeditActionPerformed(evt);
            }
        });

        nameupdate.setBackground(new java.awt.Color(0, 204, 204));
        nameupdate.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        nameupdate.setForeground(new java.awt.Color(255, 255, 255));
        nameupdate.setText("UPDATE");
        nameupdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nameupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameupdateActionPerformed(evt);
            }
        });

        cpriceedit.setBackground(new java.awt.Color(255, 0, 0));
        cpriceedit.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        cpriceedit.setForeground(new java.awt.Color(255, 255, 255));
        cpriceedit.setText("Edit");
        cpriceedit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cpriceedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpriceeditActionPerformed(evt);
            }
        });

        cpriceupdate.setBackground(new java.awt.Color(0, 204, 204));
        cpriceupdate.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        cpriceupdate.setForeground(new java.awt.Color(255, 255, 255));
        cpriceupdate.setText("UPDATE");
        cpriceupdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cpriceupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpriceupdateActionPerformed(evt);
            }
        });
        cpriceupdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cpriceupdateKeyPressed(evt);
            }
        });

        spriceedit.setBackground(new java.awt.Color(255, 0, 0));
        spriceedit.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        spriceedit.setForeground(new java.awt.Color(255, 255, 255));
        spriceedit.setText("Edit");
        spriceedit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        spriceedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spriceeditActionPerformed(evt);
            }
        });

        stockupdate.setBackground(new java.awt.Color(0, 204, 204));
        stockupdate.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        stockupdate.setForeground(new java.awt.Color(255, 255, 255));
        stockupdate.setText("UPDATE");
        stockupdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        stockupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockupdateActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("SELL PRICE ");

        sellingPriceBox.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        sellingPriceBox.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        sellingPriceBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sellingPriceBoxKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sellingPriceBoxKeyTyped(evt);
            }
        });

        stocksedit.setBackground(new java.awt.Color(255, 0, 0));
        stocksedit.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        stocksedit.setForeground(new java.awt.Color(255, 255, 255));
        stocksedit.setText("Edit");
        stocksedit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        stocksedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockseditActionPerformed(evt);
            }
        });

        spriceupdate.setBackground(new java.awt.Color(0, 204, 204));
        spriceupdate.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        spriceupdate.setForeground(new java.awt.Color(255, 255, 255));
        spriceupdate.setText("UPDATE");
        spriceupdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        spriceupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spriceupdateActionPerformed(evt);
            }
        });

        ok2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_package/images/tick.png"))); // NOI18N

        ok3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_package/images/tick.png"))); // NOI18N

        ok4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_package/images/tick.png"))); // NOI18N

        ok1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_package/images/tick.png"))); // NOI18N

        ok5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_package/images/tick.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(CloseUpdatePannel, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(21, 21, 21)
                                        .addComponent(cashPriceBox, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(21, 21, 21)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(itemCodeBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(itemNameBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(sellingPriceBox, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cpriceedit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cpriceupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ok3))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(codeedit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(codeupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(nameedit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(spriceedit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(nameupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(spriceupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(ok2)
                                                .addComponent(ok4, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addComponent(ok1, javax.swing.GroupLayout.Alignment.TRAILING)))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(45, 45, 45)
                                .addComponent(stockBox, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stocksedit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stockupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ok5)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemCodeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(codeupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(codeedit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ok1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(nameedit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(itemNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nameupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ok2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cpriceedit, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cpriceupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cashPriceBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ok3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spriceedit, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sellingPriceBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spriceupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ok4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stockBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stocksedit, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stockupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(CloseUpdatePannel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ok5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 600, 390));

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("View Items & Update");

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_package/images/unnamed.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 678, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1124, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void stockupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockupdateActionPerformed
        try {
            connect.updateStockitems("stock",stockBox.getText().trim(),primarykeyofdata);
            this.itemData[4] = stockBox.getText().trim();
            ok5.setVisible(true);
        } catch (Exception ex) {
            //System.out.println(ex);
            System.out.println(ex);
        }

        stockupdate.setEnabled(false);
        stockBox.setEditable(false);

    }//GEN-LAST:event_stockupdateActionPerformed

    private void spriceeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spriceeditActionPerformed
        sellingPriceBox.setEditable(true);

        itemCodeBox.setEditable(false);
        itemNameBox.setEditable(false);
        cashPriceBox.setEditable(false);
        stockBox.setEditable(false);

        codeupdate.setEnabled(false);
        nameupdate.setEnabled(false);
        cpriceupdate.setEnabled(false);
        spriceupdate.setEnabled(false);
        stockupdate.setEnabled(false);
    }//GEN-LAST:event_spriceeditActionPerformed

    private void cpriceupdateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cpriceupdateKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpriceupdateKeyPressed

    private void cpriceupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpriceupdateActionPerformed

        try {
            
            BigDecimal Price_cash = new BigDecimal(cashPriceBox.getText().trim());
            connect.updateStockitems("cashprice",Price_cash.toString(),primarykeyofdata);
            this.itemData[2]=cashPriceBox.getText().trim();
            ok3.setVisible(true);
        } catch (Exception ex) {
           // JOptionPane.showMessageDialog(null,"Invalid Input !");
           System.out.println(ex);
        }

        cpriceupdate.setEnabled(false);
        cashPriceBox.setEditable(false);

    }//GEN-LAST:event_cpriceupdateActionPerformed

    private void cpriceeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpriceeditActionPerformed
        cashPriceBox.setEditable(true);

        itemCodeBox.setEditable(false);
        itemNameBox.setEditable(false);
        sellingPriceBox.setEditable(false);
        stockBox.setEditable(false);

        codeupdate.setEnabled(false);
        nameupdate.setEnabled(false);
        spriceupdate.setEnabled(false);
        stockupdate.setEnabled(false);
    }//GEN-LAST:event_cpriceeditActionPerformed

    private void nameupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameupdateActionPerformed
         try {
            connect.updateStockitems("name",itemNameBox.getText().trim(),primarykeyofdata);
            this.itemData[1]=itemNameBox.getText().trim();
            ok2.setVisible(true);
        }
        catch (Exception ex) {
           // JOptionPane.showMessageDialog(null,"THIS ITEM IS ALREADY IN YOUR STOCK ! ");
           // itemCodeBox.setText(itemData[1]);
           
           System.out.println(ex);
        }

        nameupdate.setEnabled(false);
        itemNameBox.setEditable(false);
    }//GEN-LAST:event_nameupdateActionPerformed

    private void nameeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameeditActionPerformed
        itemNameBox.setEditable(true);
        
        itemCodeBox.setEditable(false);
        cashPriceBox.setEditable(false);
        sellingPriceBox.setEditable(false);
        stockBox.setEditable(false);

        codeupdate.setEnabled(false);
        cpriceupdate.setEnabled(false);
        spriceupdate.setEnabled(false);
        stockupdate.setEnabled(false);
    }//GEN-LAST:event_nameeditActionPerformed

    private void codeupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeupdateActionPerformed

        try {
            connect.updateStockitems("itemcode",itemCodeBox.getText().trim(),primarykeyofdata);
            this.itemData[0]=itemCodeBox.getText().trim();
            primarykeyofdata = itemCodeBox.getText().trim(); // setting new primary key
            ok1.setVisible(true);
        }
        catch (Exception ex) {
           // JOptionPane.showMessageDialog(null,"THIS ITEM IS ALREADY IN YOUR STOCK ! ");
           // itemCodeBox.setText(itemData[0]);
            System.out.println(ex);
        }
        
        
        

        codeupdate.setEnabled(false);
        itemCodeBox.setEditable(false);
    }//GEN-LAST:event_codeupdateActionPerformed

    private void codeeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeeditActionPerformed
        itemCodeBox.setEditable(true);

        itemNameBox.setEditable(false);
        cashPriceBox.setEditable(false);
        stockBox.setEditable(false);
        stockBox.setEditable(false);
        sellingPriceBox.setEditable(false);
        
        nameupdate.setEnabled(false);
        cpriceupdate.setEnabled(false);
        spriceupdate.setEnabled(false);
        stockupdate.setEnabled(false);
        
        if(itemNameBox.getText().trim().equals(""))
            {
                itemNameBox.setText(itemData[1]);
            }
        if(cashPriceBox.getText().trim().isEmpty())
            {
                cashPriceBox.setText(itemData[2]);
            }
        if(sellingPriceBox.getText().trim().isEmpty())
            {
                sellingPriceBox.setText(itemData[3]);
            }
        if(stockBox.getText().trim().isEmpty())
            {
                stockBox.setText(itemData[4]);
            }
        
    }//GEN-LAST:event_codeeditActionPerformed

    private void CloseUpdatePannelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseUpdatePannelActionPerformed
   
        try {
            //DISPLAYING UPDATE TABLE TO THE USER
            stocks.clearTable();
            connect.stockItemsShowAll();
           
        } catch (Exception e) {
            System.out.println(e);
        }
        
         setVisible(false);

    }//GEN-LAST:event_CloseUpdatePannelActionPerformed

    private void stockBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stockBoxKeyTyped
        char character = evt.getKeyChar();
        String lenth = stockBox.getText();

        if(lenth.length()==10)
        {
            evt.consume();
        }

        if((Character.isDigit(character)) || Character.isISOControl(character) && lenth.length()>1)
        {
            stockBox.setEnabled(true);
            stockupdate.setEnabled(true);
        }
        else
        {
            evt.consume();
            stockupdate.setEnabled(false);
        }
    }//GEN-LAST:event_stockBoxKeyTyped

    private void stockBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stockBoxKeyReleased
        String lenth=stockBox.getText();
        if(lenth.length()>0)
        {
            stockupdate.setEnabled(true);
        }
        else
        {
            stockupdate.setEnabled(false);
        }
    }//GEN-LAST:event_stockBoxKeyReleased

    private void cashPriceBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cashPriceBoxKeyTyped
        char charactor = evt.getKeyChar();
        String lenth = cashPriceBox.getText();

        if(lenth.length()==16)
        {
            evt.consume();
        }
        
          
    //CHAKING IF ALREADY " . " IN TEXT BOX
        if(!lenth.contains("."))
            {
                dot=false;
                
            }

         // IF DOT HAS TYPED THIS PART WILL BW RUN
        if(dot == false)
            {
                            if ((Character.isDigit(charactor)) || (Character.isISOControl(charactor)) || charactor == KeyEvent.VK_PERIOD)
                            {
                               cashPriceBox.setEditable(true);
                                
                            } else {
                                
                               evt.consume();
                            }
                             
            }
        
        else
            {
   // IF DOT DOES NOT HAS TYPED THIS PART WILL RUN
                            if ((Character.isDigit(charactor)) || (Character.isISOControl(charactor)) )
                                {
                                    if(lenth.length() == lenth.indexOf(".")+3)
                                        {
                                         evt.consume();
                                        }
                                }
                            else
                                {
                                       evt.consume();
                                }
            }
   

    //MAKE dot VARIABLE TRUE IF USER PRESSED " . "
        if(charactor == KeyEvent.VK_PERIOD)
            {
                dot = true;
           }

    
    
    }//GEN-LAST:event_cashPriceBoxKeyTyped

    private void cashPriceBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cashPriceBoxKeyReleased
        String lenth = cashPriceBox.getText();

        if(lenth.length()>0)
        {
            cpriceupdate.setEnabled(true);
        }
        else
        {
            cpriceupdate.setEnabled(false);
        }
    }//GEN-LAST:event_cashPriceBoxKeyReleased

    private void cashPriceBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashPriceBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cashPriceBoxActionPerformed

    private void itemNameBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemNameBoxKeyTyped
        char character = evt.getKeyChar();
        String lenth = itemNameBox.getText();

        if(lenth.length()==100)
        {
            evt.consume();
        }

    }//GEN-LAST:event_itemNameBoxKeyTyped

    private void itemNameBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemNameBoxKeyReleased
        String lenth = itemNameBox.getText();

        if(lenth.length()>0)
        {
            nameupdate.setEnabled(true);
        }
        else
        {
            nameupdate.setEnabled(false);
        }
    }//GEN-LAST:event_itemNameBoxKeyReleased

    private void itemCodeBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemCodeBoxKeyTyped
        String lenth = itemCodeBox.getText();

        if(lenth.length()==30)
        {
            evt.consume();
        }

    }//GEN-LAST:event_itemCodeBoxKeyTyped

    private void itemCodeBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemCodeBoxKeyReleased
        String lenth = itemCodeBox.getText();

        if(lenth.length()>0)
        {
            codeupdate.setEnabled(true);
        }
        else
        {
            codeupdate.setEnabled(false);
        }
    }//GEN-LAST:event_itemCodeBoxKeyReleased

    private void itemCodeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCodeBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemCodeBoxActionPerformed

    private void sellingPriceBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sellingPriceBoxKeyReleased
        String lenth = sellingPriceBox.getText();

        if(lenth.length()>0)
        {
            spriceupdate.setEnabled(true);
        }
        else
        {
            spriceupdate.setEnabled(false);
        }
    }//GEN-LAST:event_sellingPriceBoxKeyReleased

    private void sellingPriceBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sellingPriceBoxKeyTyped
         char character = evt.getKeyChar();
        String lenth = sellingPriceBox.getText();

        if(lenth.length()==10)
        {
            evt.consume();
        }

        if((Character.isDigit(character)) || Character.isISOControl(character) && lenth.length()>1 || character==KeyEvent.VK_PERIOD)
        {
            sellingPriceBox.setEnabled(true);
            spriceupdate.setEnabled(true);
        }
        else
        {
            evt.consume();
            spriceupdate.setEnabled(false);
        }
    }//GEN-LAST:event_sellingPriceBoxKeyTyped

    private void stockseditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockseditActionPerformed
        stockBox.setEditable(true);
        
        itemCodeBox.setEditable(false);
        itemNameBox.setEditable(false);
        cashPriceBox.setEditable(false);
        sellingPriceBox.setEditable(false);
        
        codeupdate.setEnabled(false);
        nameupdate.setEnabled(false);
        cpriceupdate.setEnabled(false);
        spriceupdate.setEnabled(false);
        stockupdate.setEnabled(false);
        
        
    }//GEN-LAST:event_stockseditActionPerformed

    private void spriceupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spriceupdateActionPerformed
          try {
              
            BigDecimal selprice = new BigDecimal(sellingPriceBox.getText().trim());
            connect.updateStockitems("sellprice",selprice.toString(),primarykeyofdata);
            this.itemData[3]=sellingPriceBox.getText().trim();
            ok4.setVisible(true);
            
        } catch (Exception ex) {
          //  JOptionPane.showMessageDialog(null , "Invalid Input !");
          System.out.println(ex);
        }

        spriceupdate.setEnabled(false);
        sellingPriceBox.setEditable(false);
    }//GEN-LAST:event_spriceupdateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         //seting all fields to default values
        itemCodeBox.setText(itemData[0]);
        itemNameBox.setText(itemData[1]);
        cashPriceBox.setText(itemData[2]);
        sellingPriceBox.setText(itemData[3]);
        stockBox.setText(itemData[4]);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stock_item_display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stock_item_display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stock_item_display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stock_item_display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try
                   {
                       new stock_item_display("","","","","").setVisible(true);
                   }
                catch(Exception e)
                    {
                    
                    }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseUpdatePannel;
    private javax.swing.JTextField cashPriceBox;
    private javax.swing.JButton codeedit;
    private javax.swing.JButton codeupdate;
    private javax.swing.JButton cpriceedit;
    private javax.swing.JButton cpriceupdate;
    private javax.swing.JTextField itemCodeBox;
    private javax.swing.JTextField itemNameBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton nameedit;
    private javax.swing.JButton nameupdate;
    private javax.swing.JLabel ok1;
    private javax.swing.JLabel ok2;
    private javax.swing.JLabel ok3;
    private javax.swing.JLabel ok4;
    private javax.swing.JLabel ok5;
    private javax.swing.JTextField sellingPriceBox;
    private javax.swing.JButton spriceedit;
    private javax.swing.JButton spriceupdate;
    private javax.swing.JTextField stockBox;
    private javax.swing.JButton stocksedit;
    private javax.swing.JButton stockupdate;
    // End of variables declaration//GEN-END:variables
}
